In [8]:
2+2

4

In [9]:
2+3

5

In [10]:
+2

2

In [12]:
number = 5

In [13]:
number + 3

8

## 3. Pandas

In [14]:
import pandas as pd

In [15]:
my_list = [2,4,6,8,9,11,3]

In [16]:
my_series = pd.Series(my_list)

In [17]:
my_series.sum()

43

In [18]:
my_series.max()

11

In [19]:
my_series.min()

2

In [20]:
my_series.mean()

6.142857142857143

In [21]:
my_series.describe()

count     7.000000
mean      6.142857
std       3.338092
min       2.000000
25%       3.500000
50%       6.000000
75%       8.500000
max      11.000000
dtype: float64

## 4. Data

LA Times, The Robinson R44

In [22]:
accident_list = pd.read_csv("https://raw.githubusercontent.com/palewire/first-python-notebook/main/docs/src/_static/ntsb-accidents.csv")

In [23]:
accident_list

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
0,20061222X01838,BELL,407,NYC07FA048,2006,12/14/06 00:00:00,DAGSBORO,DE,USA,2,BELL,407,BELL 407
1,20060817X01187,ROBINSON,R22 BETA,LAX06LA257,2006,08/10/06 00:00:00,TUCSON,AZ,USA,1,ROBINSON,R22,ROBINSON R22
2,20060111X00044,ROBINSON,R44,MIA06FA039,2006,01/01/06 00:00:00,GRAND RIDGE,FL,USA,3,ROBINSON,R44,ROBINSON R44
3,20060419X00461,ROBINSON,R44 II,DFW06FA102,2006,04/13/06 00:00:00,FREDERICKSBURG,TX,USA,2,ROBINSON,R44,ROBINSON R44
4,20060208X00181,ROBINSON,R44,SEA06LA052,2006,02/06/06 00:00:00,HELENA,MT,USA,1,ROBINSON,R44,ROBINSON R44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,20160711X32921,BELL HELICOPTER TEXTRON CANADA,407,ERA16FA248,2016,07/11/16 00:00:00,HICKORY,KY,USA,1,BELL,407,BELL 407
159,20160804X45514,SCHWEIZER,269C 1,CEN16FA304,2016,08/03/16 00:00:00,JEANERETTE,LA,USA,1,SCHWEIZER,269,SCHWEIZER 269
160,20160404X74644,BELL,206,ERA16FA144,2016,04/04/16 00:00:00,PIGEON FORGE,TN,USA,5,BELL,206,BELL 206
161,20160507X31120,AIRBUS,AS350,ANC16FA023,2016,05/06/16 00:00:00,SKAGWAY,AK,USA,1,AIRBUS,350,AIRBUS 350
162,20160612X85856,ROBINSON HELICOPTER COMPANY,R44 II,CEN16FA215,2016,06/12/16 00:00:00,JONESBORO,AR,USA,1,ROBINSON,R44,ROBINSON R44

In [24]:
accident_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                163 non-null    object
 1   ntsb_make               163 non-null    object
 2   ntsb_model              163 non-null    object
 3   ntsb_number             163 non-null    object
 4   year                    163 non-null    int64
 5   date                    163 non-null    object
 6   city                    163 non-null    object
 7   state                   162 non-null    object
 8   country                 163 non-null    object
 9   total_fatalities        163 non-null    int64
 10  latimes_make            163 non-null    object
 11  latimes_model           163 non-null    object
 12  latimes_make_and_model  163 non-null    object
dtypes: int64(2), object(11)
memory usage: 16.7+ KB

In [25]:
accident_list['latimes_make_and_model']

0           BELL 407
1       ROBINSON R22
2       ROBINSON R44
3       ROBINSON R44
4       ROBINSON R44
           ...
158         BELL 407
159    SCHWEIZER 269
160         BELL 206
161       AIRBUS 350
162     ROBINSON R44
Name: latimes_make_and_model, Length: 163, dtype: object

In [26]:
accident_list.latimes_make_and_model.value_counts()

latimes_make_and_model
ROBINSON R44             38
BELL 206                 30
AIRBUS 350               29
ROBINSON R22             20
BELL 407                 13
HUGHES 369               13
MCDONNELL DOUGLAS 369     6
SCHWEIZER 269             5
AIRBUS 135                4
SIKORSKY 76               2
AGUSTA 109                2
AIRBUS 130                1
Name: count, dtype: int64

In [27]:
# Convert ugly Series into a pretty DataFrame by adding reset_index:
accident_list['latimes_make_and_model'].value_counts().reset_index()

   latimes_make_and_model  count
0            ROBINSON R44     38
1                BELL 206     30
2              AIRBUS 350     29
3            ROBINSON R22     20
4                BELL 407     13
5              HUGHES 369     13
6   MCDONNELL DOUGLAS 369      6
7           SCHWEIZER 269      5
8              AIRBUS 135      4
9             SIKORSKY 76      2
10             AGUSTA 109      2
11             AIRBUS 130      1

# Quick Challenge:
What was the total number of fatalities? 336

Which helicopter maker had the most accidents? ROBINSON

What was the total number of helicopter accidents by year?
	year	count
0	2008	22
1	2006	20
2	2010	18
3	2013	18
4	2014	17
5	2007	16
6	2012	16
7	2009	15
8	2015	11
9	2016	10

Which state had the most helicopter accidents? CA

In [28]:
list(accident_list)

['event_id',
 'ntsb_make',
 'ntsb_model',
 'ntsb_number',
 'year',
 'date',
 'city',
 'state',
 'country',
 'total_fatalities',
 'latimes_make',
 'latimes_model',
 'latimes_make_and_model']

In [29]:
accident_list.total_fatalities.sum()

336

In [30]:
accident_list.latimes_make.value_counts()

latimes_make
ROBINSON             58
BELL                 43
AIRBUS               34
HUGHES               13
MCDONNELL DOUGLAS     6
SCHWEIZER             5
SIKORSKY              2
AGUSTA                2
Name: count, dtype: int64

In [31]:
accident_list['year'].value_counts().reset_index()

   year  count
0  2008     22
1  2006     20
2  2010     18
3  2013     18
4  2014     17
5  2007     16
6  2012     16
7  2009     15
8  2015     11
9  2016     10

In [32]:
accident_list.state.value_counts().reset_index()

   state  count
0     CA     16
1     TX     15
2     AZ     14
3     FL      9
4     WA      8
5     LA      8
6     TN      6
7     AK      6
8     AL      5
9     UT      5
10    OK      5
11    MT      4
12    HI      4
13    MO      4
14    OR      4
15    GM      3
16    WI      3
17    KY      3
18    PA      3
19    NM      3
20    CO      3
21    IA      3
22    IN      2
23    NV      2
24    NC      2
25    MD      2
26    AR      2
27    VA      2
28    MS      2
29    NY      2
30    MA      1
31    WV      1
32    WY      1
33    DE      1
34    GA      1
35    KS      1
36    NJ      1
37    SC      1
38    MI      1
39    DC      1
40    ID      1
41    PR      1

## 6. Filter

In [33]:
my_state = 'MI'

In [34]:
mi_accidents = accident_list[accident_list['state'] == my_state]

In [35]:
mi_accidents.head()

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
11,20060419X00457,ROBINSON,R22 BETA,CHI06FA109,2006,04/13/06 00:00:00,CHELSEA,MI,USA,2,ROBINSON,R22,ROBINSON R22

In [36]:
mi_accidents.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 11 to 11
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                1 non-null      object
 1   ntsb_make               1 non-null      object
 2   ntsb_model              1 non-null      object
 3   ntsb_number             1 non-null      object
 4   year                    1 non-null      int64
 5   date                    1 non-null      object
 6   city                    1 non-null      object
 7   state                   1 non-null      object
 8   country                 1 non-null      object
 9   total_fatalities        1 non-null      int64
 10  latimes_make            1 non-null      object
 11  latimes_model           1 non-null      object
 12  latimes_make_and_model  1 non-null      object
dtypes: int64(2), object(11)
memory usage: 112.0+ bytes

In [37]:
def get_state_result(fstate):
    state_accidents = accident_list[accident_list['state'] == fstate]
    print(len(state_accidents))
    print(state_accidents.info())

In [38]:
get_state_result('IA')

3
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 12 to 140
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                3 non-null      object
 1   ntsb_make               3 non-null      object
 2   ntsb_model              3 non-null      object
 3   ntsb_number             3 non-null      object
 4   year                    3 non-null      int64
 5   date                    3 non-null      object
 6   city                    3 non-null      object
 7   state                   3 non-null      object
 8   country                 3 non-null      object
 9   total_fatalities        3 non-null      int64
 10  latimes_make            3 non-null      object
 11  latimes_model           3 non-null      object
 12  latimes_make_and_model  3 non-null      object
dtypes: int64(2), object(11)
memory usage: 336.0+ bytes
None

In [39]:
get_state_result('MO')

4
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 55 to 144
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                4 non-null      object
 1   ntsb_make               4 non-null      object
 2   ntsb_model              4 non-null      object
 3   ntsb_number             4 non-null      object
 4   year                    4 non-null      int64
 5   date                    4 non-null      object
 6   city                    4 non-null      object
 7   state                   4 non-null      object
 8   country                 4 non-null      object
 9   total_fatalities        4 non-null      int64
 10  latimes_make            4 non-null      object
 11  latimes_model           4 non-null      object
 12  latimes_make_and_model  4 non-null      object
dtypes: int64(2), object(11)
memory usage: 448.0+ bytes
None

Which state recorded more accidents, Iowa or Missouri? Missouri (MO)

How many accidents recorded more than one fatality? 89

How many accidents happened in California in 2015? 2

What percentage of the total fatalities occured in California? 9.5%

In [40]:
accident_list[accident_list['total_fatalities'] >= 2]

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
0,20061222X01838,BELL,407,NYC07FA048,2006,12/14/06 00:00:00,DAGSBORO,DE,USA,2,BELL,407,BELL 407
2,20060111X00044,ROBINSON,R44,MIA06FA039,2006,01/01/06 00:00:00,GRAND RIDGE,FL,USA,3,ROBINSON,R44,ROBINSON R44
3,20060419X00461,ROBINSON,R44 II,DFW06FA102,2006,04/13/06 00:00:00,FREDERICKSBURG,TX,USA,2,ROBINSON,R44,ROBINSON R44
5,20060228X00255,ROBINSON,R22,ANC06FA020,2006,02/22/06 00:00:00,SCOTTSDALE,AZ,USA,2,ROBINSON,R22,ROBINSON R22
6,20060824X01237,EUROCOPTER,AS-350-B3,SEA06GA158,2006,08/13/06 00:00:00,YELLOW PINE,ID,USA,4,AIRBUS,350,AIRBUS 350
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,20151216X13718,AIRBUS HELICOPTERS,AS350,WPR16FA040,2015,12/15/15 00:00:00,SUPERIOR,AZ,USA,2,AIRBUS,350,AIRBUS 350
152,20151118X05037,AIRBUS HELICOPTERS,AS350B3E,WPR16FA029,2015,11/18/15 00:00:00,CARLSBAD,CA,USA,2,AIRBUS,350,AIRBUS 350
153,20161116X00108,HUGHES,369D/500D,WPR17FA021,2016,11/15/16 00:00:00,PUKOO,HI,USA,2,HUGHES,369,HUGHES 369
154,20160326X80544,EUROCOPTER,AS 350 B2,ERA16FA140,2016,03/26/16 00:00:00,ENTERPRISE,AL,USA,4,AIRBUS,350,AIRBUS 350
160,20160404X74644,BELL,206,ERA16FA144,2016,04/04/16 00:00:00,PIGEON FORGE,TN,USA,5,BELL,206,BELL 206

In [41]:
accident_list[(accident_list['state'] == 'CA') & (accident_list['year'] == 2015)]

,event_id,ntsb_make,ntsb_model,ntsb_number,year,date,city,state,country,total_fatalities,latimes_make,latimes_model,latimes_make_and_model
148,20151211X13514,BELL,407,WPR16FA037,2015,12/10/15 00:00:00,MCFARLAND,CA,USA,4,BELL,407,BELL 407
152,20151118X05037,AIRBUS HELICOPTERS,AS350B3E,WPR16FA029,2015,11/18/15 00:00:00,CARLSBAD,CA,USA,2,AIRBUS,350,AIRBUS 350

In [42]:
total_fatalities_ca = accident_list[(accident_list['state'] == 'CA') & (accident_list['total_fatalities'] > 0)].total_fatalities.sum()

In [43]:
(total_fatalities_ca/accident_list.total_fatalities.sum())*100

9.523809523809524

## 7. Group

In [75]:
accident_counts = accident_list.groupby(['latimes_make', 'latimes_make_and_model']).size().rename('accidents').reset_index() # size gives total, similar to value_counts

In [76]:
# sum total fatalities for each maker
accident_list.groupby('latimes_make_and_model')['total_fatalities'].sum().reset_index()

   latimes_make_and_model  total_fatalities
0              AGUSTA 109                 5
1              AIRBUS 130                 1
2              AIRBUS 135                11
3              AIRBUS 350                81
4                BELL 206                61
5                BELL 407                35
6              HUGHES 369                19
7   MCDONNELL DOUGLAS 369                 7
8            ROBINSON R22                27
9            ROBINSON R44                71
10          SCHWEIZER 269                 7
11            SIKORSKY 76                11

In [77]:
accident_counts.head()

  latimes_make latimes_make_and_model  accidents
0       AGUSTA             AGUSTA 109          2
1       AIRBUS             AIRBUS 130          1
2       AIRBUS             AIRBUS 135          4
3       AIRBUS             AIRBUS 350         29
4         BELL               BELL 206         30

## 8. Merge

In [78]:
survey = pd.read_csv("https://raw.githubusercontent.com/palewire/first-python-notebook/main/docs/src/_static/faa-survey.csv")

In [79]:
survey.head()

  latimes_make_and_model  total_hours
0             AGUSTA 109       362172
1             AIRBUS 130      1053786
2             AIRBUS 135       884596
3             AIRBUS 350      3883490
4               BELL 206      5501308

In [80]:
accident_counts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   latimes_make            12 non-null     object
 1   latimes_make_and_model  12 non-null     object
 2   accidents               12 non-null     int64
dtypes: int64(1), object(2)
memory usage: 416.0+ bytes

In [81]:
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   latimes_make_and_model  12 non-null     object
 1   total_hours             12 non-null     int64
dtypes: int64(1), object(1)
memory usage: 320.0+ bytes

In [82]:
merged_list = pd.merge(accident_counts, survey, on="latimes_make_and_model")

In [83]:
merged_list.head()

  latimes_make latimes_make_and_model  accidents  total_hours
0       AGUSTA             AGUSTA 109          2       362172
1       AIRBUS             AIRBUS 130          1      1053786
2       AIRBUS             AIRBUS 135          4       884596
3       AIRBUS             AIRBUS 350         29      3883490
4         BELL               BELL 206         30      5501308

In [84]:
merged_list.info() # if there are no null values, that means every record in each df found a match in the other

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   latimes_make            12 non-null     object
 1   latimes_make_and_model  12 non-null     object
 2   accidents               12 non-null     int64
 3   total_hours             12 non-null     int64
dtypes: int64(2), object(2)
memory usage: 512.0+ bytes

## 9. Compute
creating a new column based on data in other colums is a process known as computing

In [85]:
merged_list['per_hour'] = merged_list['accidents']/merged_list['total_hours']

In [86]:
merged_list.head()

  latimes_make latimes_make_and_model  accidents  total_hours      per_hour
0       AGUSTA             AGUSTA 109          2       362172  5.522238e-06
1       AIRBUS             AIRBUS 130          1      1053786  9.489593e-07
2       AIRBUS             AIRBUS 135          4       884596  4.521838e-06
3       AIRBUS             AIRBUS 350         29      3883490  7.467510e-06
4         BELL               BELL 206         30      5501308  5.453249e-06

In [87]:
merged_list['per_100k_hours'] = merged_list['per_hour'] * 100_000

In [88]:
merged_list.head()

,latimes_make,latimes_make_and_model,accidents,total_hours,per_hour,per_100k_hours
0,AGUSTA,AGUSTA 109,2,362172,5.522238e-06,0.552224
1,AIRBUS,AIRBUS 130,1,1053786,9.489593e-07,0.094896
2,AIRBUS,AIRBUS 135,4,884596,4.521838e-06,0.452184
3,AIRBUS,AIRBUS 350,29,3883490,7.467510e-06,0.746751
4,BELL,BELL 206,30,5501308,5.453249e-06,0.545325

## 10. Sort

In [89]:
merged_list.sort_values('per_100k_hours', ascending=False) # ascending = False to get highest value at the top

,latimes_make,latimes_make_and_model,accidents,total_hours,per_hour,per_100k_hours
9,ROBINSON,ROBINSON R44,38,2359729,1.610354e-05,1.610354
7,MCDONNELL DOUGLAS,MCDONNELL DOUGLAS 369,6,550689,1.089544e-05,1.089544
6,HUGHES,HUGHES 369,13,1201688,1.081812e-05,1.081812
3,AIRBUS,AIRBUS 350,29,3883490,7.467510e-06,0.746751
8,ROBINSON,ROBINSON R22,20,2970806,6.732180e-06,0.673218
5,BELL,BELL 407,13,2113788,6.150096e-06,0.615010
0,AGUSTA,AGUSTA 109,2,362172,5.522238e-06,0.552224
4,BELL,BELL 206,30,5501308,5.453249e-06,0.545325
2,AIRBUS,AIRBUS 135,4,884596,4.521838e-06,0.452184
10,SCHWEIZER,SCHWEIZER 269,5,1139326,4.388560e-06,0.438856
11,SIKORSKY,SIKORSKY 76,2,915515,2.184563e-06,0.218456
1,AIRBUS,AIRBUS 130,1,1053786,9.489593e-07,0.094896

## 11. Charts

In [59]:
pip install altair

Looking in indexes: https://pypi.org/simple, https://pypi.ghgsat.com/simple/
Requirement already satisfied: altair in ./jupyterenv/lib/python3.8/site-packages (5.1.1)
Requirement already satisfied: jsonschema>=3.0 in ./jupyterenv/lib/python3.8/site-packages (from altair) (4.19.0)
Requirement already satisfied: numpy in ./jupyterenv/lib/python3.8/site-packages (from altair) (1.24.4)
Requirement already satisfied: pandas>=0.25 in ./jupyterenv/lib/python3.8/site-packages (from altair) (2.0.3)
Requirement already satisfied: toolz in ./jupyterenv/lib/python3.8/site-packages (from altair) (0.12.0)
Requirement already satisfied: packaging in ./jupyterenv/lib/python3.8/site-packages (from altair) (23.1)
Requirement already satisfied: typing-extensions>=4.0.1; python_version < "3.11" in ./jupyterenv/lib/python3.8/site-packages (from altair) (4.7.1)
Requirement already satisfied: jinja2 in ./jupyterenv/lib/python3.8/site-packages (from altair) (3.1.2)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10; python_version < "3.9" in ./jupyterenv/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (1.3.10)
Requirement already satisfied: rpds-py>=0.7.1 in ./jupyterenv/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (0.9.2)
Requirement already satisfied: importlib-resources>=1.4.0; python_version < "3.9" in ./jupyterenv/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (6.0.1)
Requirement already satisfied: referencing>=0.28.4 in ./jupyterenv/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (0.30.2)
Requirement already satisfied: attrs>=22.2.0 in ./jupyterenv/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./jupyterenv/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (2023.7.1)
Requirement already satisfied: pytz>=2020.1 in ./jupyterenv/lib/python3.8/site-packages (from pandas>=0.25->altair) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./jupyterenv/lib/python3.8/site-packages (from pandas>=0.25->altair) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in ./jupyterenv/lib/python3.8/site-packages (from pandas>=0.25->altair) (2023.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./jupyterenv/lib/python3.8/site-packages (from jinja2->altair) (2.1.3)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in ./jupyterenv/lib/python3.8/site-packages (from importlib-resources>=1.4.0; python_version < "3.9"->jsonschema>=3.0->altair) (3.16.2)
Requirement already satisfied: six>=1.5 in ./jupyterenv/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=0.25->altair) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [90]:
import altair as alt

In [91]:
alt.Chart(merged_list).mark_bar().encode(y="latimes_make_and_model", x="per_100k_hours")

alt.Chart(...)

In [92]:
alt.Chart(merged_list).mark_bar().encode(x="per_100k_hours", y=alt.Y("latimes_make_and_model", sort="-x")).properties(title="Helicopter accident rates")

alt.Chart(...)

In [93]:
alt.Chart(merged_list).mark_circle().encode(size="per_100k_hours", y=alt.Y("latimes_make_and_model", sort="-size"), tooltip="per_100k_hours")

alt.Chart(...)

In [97]:
alt.Chart(merged_list).mark_bar().encode(x='per_100k_hours',y=alt.Y('latimes_make_and_model', sort='-x'), color='latimes_make').properties(title="Helicopter accident rates")

alt.Chart(...)

In [106]:
alt.Chart(merged_list).mark_bar().encode(x='per_100k_hours',
                                         y=alt.Y('latimes_make_and_model', sort='-x'), 
                                         color=alt.condition(
                                             alt.datum.latimes_make=="ROBINSON",
                                             alt.value("purple"),
                                             alt.value('pink')
                                         )
                                        ).properties(title="Helicopter accident rates")

alt.Chart(...)

In [109]:
#convert an object type to a date type 
accident_list['date'] = pd.to_datetime(accident_list['date'])

In [113]:
alt.Chart(accident_list).mark_bar().encode(x="date", y="total_fatalities")

alt.Chart(...)

In [116]:
alt.Chart(accident_list).mark_bar().encode(x="yearmonth(date)", y="sum(total_fatalities)")

alt.Chart(...)

In [117]:
alt.Chart(accident_list).mark_bar().encode(x="yearmonth(date)", y="sum(total_fatalities)", facet="latimes_make")

alt.Chart(...)

## 12. Export

In [120]:
merged_list.to_csv('accident-rate-ranking.csv', index=False, sep=";")

![datawrapper](datawrapper-accident-rate-ranking.png)

In [121]:
# https://palewi.re/docs/first-python-notebook/appendix/index.html

## SUMMARY of things we learnt

- Panda series turn lists into more useful things that we can `.max(), .min(), .sum(), .mean(), .describe()`
- You can import data from a url using `pd.read_csv(url)`
- A Series in 1 dimensional, and a dataframe is 2 dimensional
- df.info() tells you stuff about the df
- You can do lots of things with dataframes! Eg. `df['column']` or df.column to list a specific column. Then you can append `.sum()` to a specific column to total that column, or add `.value_counts()` to sum up the different values in that column.
- `.reset_index()` turns un ugly series into a pretty dataframe
- `list(df)` gives you all the column headers of the df
- `df.head()` gives you the first 5 entries in a df. You can tailor this to get more or less by adding a number to the function eg. `df.head(1)` will only return the first entry. Good habit to get into if you want to take a quick look without loading all the data.
-  You can filter what you get back from a df by doing `df[df['column'] == x]` where x is a value in that column
-  You can have two filters by doing `df[(df['col1'] == 'x') & (df['col2'] == y)]`, don't forget brackets!
-  You can append `.col_name.sum()` to the filter condition to only return the total of a specified column
-  `len(df)` will give you the number of entries / rows in the df
-  You can group things too: `new_counts = df.groupby(['col1', 'col2']).size().rename('new_name').reset_index() # size gives total number of instances, similar to value_counts`


### Merging two pds:
1. Get second df using `df2 = pd.read_csv(url2)`
2. Use `df1.info()` and `df2.info()` to find a shared_column these two dfs can be joined on
3. Do `merged_list = pd.merge(df1, df2, on="shared_column")`

- Compute a new Column: `merged_list['new_col_name'] = merged_list['col1']/merged_list['col2']`
- Sort: `merged_list.sort_values('col1', ascending=False) # ascending = False to get highest value at the top`

### Charts with Altair
`import altair as alt`
`alt.Chart(merged_list).mark_bar().encode(x="col1", y=alt.Y("col2", sort="-x")).properties(title="TITLE")`
```
alt.Chart(merged_list).mark_bar().encode(x='col1',
                                         y=alt.Y('col2', sort='-x'), 
                                         color=alt.condition(
                                             alt.datum.col2=="VALUE",
                                             alt.value("purple"),
                                             alt.value('pink')
                                         )
                                        ).properties(title="TITLE")
```

- Specify the type of a column eg. object to datetime: `df['date'] = pd.to_datetime(accident_list['date'])`
`alt.Chart(df).mark_bar().encode(x="yearmonth(date)", y="sum(col1)")`  

- Export data: `merged_list.to_csv('title.csv', index=False, sep=";")`